package com.sudoku.core.solver;
public enum Technique {
    NAKED_SINGLE, HIDDEN_SINGLE, NAKED_PAIR, HIDDEN_PAIR, TRIPLE,
    POINTING_PAIR, INTERSECTION, BOX_REDUCTION, X_WING, SWORDFISH, XY_WING, FORCING_CHAIN
}
